name: sociedade_primitiva_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.5
  fake_cloud_firestore: ^2.4.1+1
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  freezed_annotation: ^2.4.1
  go_router: ^10.0.0
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  riverpod_generator: ^2.2.6

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
